### ISSUE TITLE
Only allow traffic from offical ips

### ISSUE THREAD

**Issue by Jellyfrog** [danheberden/gith#13]
Since GitHub specifies from which IPs they will send the request, gith should only accept data from these (and optionally some specified ones)

```
The Public IP addresses for these hooks are:
207.97.227.253,
50.57.128.197,
108.171.174.178,
50.57.231.61.
```

This info can be found under Settings > Service Hooks > WebHook URLs

**Comment by lboecker** [comment]
+1
