### ISSUE TITLE
end never call on GitHub Test

### ISSUE THREAD

**Issue by orefalo** [danheberden/gith#8]
node 8.9, connectivity confirmed, testing from github hook panel (Test Hook button)

For some obscur reason, the end event is not being called.

**gith.js**

```
this.server = http.createServer( function( req, res ) {
var data = "";
if ( req.method === "POST" ) {
  req.on( "data", function( chunk ) {
     /// I DO SEE CHUNK BEING APPENED TO DATA
    data += chunk;
  });
}

req.on( "end", function() { // <<--- THIS GUY NEVER GETS CALLED
  if ( /^payload=/.test( data ) ) {
    var payload = JSON.parse( querystring.unescape(data.slice(8)) );
    eventaur.emit( "payload", payload );
  }
  res.end();
});

res.writeHead( 200, {
  'Content-type': 'text/html'
});
res.end();
  }).listen( port );
```

Since **end** doesn't get called, gith just never picks up any message....

**Comment by danheberden** [comment]
I've had issues with github's test hook button not working at all - was it still getting data?

**Comment by orefalo** [comment]
Yes, you do get the data in the chunk... but "end" never gets called.  not sure why...

**Comment by orefalo** [comment]
Hey, do you actually have it working somewhere ? because it just doesn't work and I've been scratching my days two evenings on it

**Comment by orefalo** [comment]
FYI, this node webhook works fine. https://github.com/nathan-lafreniere/node-github-hook

The API is not as fancy as yours but it does get the payload properly

**Comment by danheberden** [comment]
It was closing the request before it was complete - it must have passed the local tests due to no latency on the chunks. Either way, all fixed :)
